version: '3' #To use this make sure that you have an edge group that has the name gitops
services:
 alpine-gitops:
  image: alpine
  tty: true
  stdin_open: true
  deploy:
   mode: global
  environment:
   - ${ENV:-test}=full-life
  volumes:
   - ./html/${PORTAINER_EDGE_GROUP}:/home/config-edgegroup
