version: '3.4' #To use this make sure that you have an edge group that has the name gitops
services:
 alpine-gitops:
  image: alpine
  tty: true
  stdin_open: true
  environment:
   - ${ENV:-test}=full-life
   - major=uppdate
   - asd=zxc

  volumes:
   - ./html/${PORTAINER_EDGE_GROUP}:/home/config-edgegroup

