version: '3'
services:
 large-app:
  image: alpine:latest
  volumes:
      - ../html:/home/html
  tty: true
  stdin_open: true
 other-large-app:
  image: nats
  volumes:
   - ../private:/home/private


   
