version: '3'
services:
 large-app:
  image: 6261998/priv:latest
  volumes:
      - ../html:/home/html
  tty: true
  stdin_open: true
  environment:
   - ${ENV:-default}=novigrad
   - ${ENV2:-default2}=raphael
   - somethig=test
   